### ISSUE TITLE
UUID branch

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#225]
- [x] the only ID for player profiles becomes the UUID (generated by Guid() at creation)
- [x] the savePlayers in plyerPrefs is public List<PlayerIconData> SavedPlayers; in AppSettings
- [x]  the profile selector (in both Start and Reserved Area) use the new PlayerIconPrefab
- [x]  the PlayerProfileManager provides easy methods to manage this List
- [x] the saved DB have this filenames: AnturaPlayer_uuid.sqlite3
- [x] the powerupped player have the IsGod = true (and special icon)
