### ISSUE TITLE
[MiniGame] DancingDots_letterform

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#540]
NEW variation, Keep only if removing the dots is possible

Must have
- [ ] check new SetupBuilder()
- [ ] Remove dots part in the gameplay, and keep only diacritic signs (it’s the focus of this game now)

Nice to have
- [ ] Keep the shadow/preview of the diacritic position on the dancing letter constantly visible

**Comment by CatmanIta** [comment]
I tried modifying this, but the code is really messy. There is no easy way to separate dots from diacritics, as the game does not really use the question builder (it ignores diacritics, adds them where needed)
