### ISSUE TITLE
[Assessment] Assessment_LetterForm

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#565]
NEW variation

- [x] check  AssessmentConfiguration.Setup_LetterForm_Builder()
- [ ] rework ArabicAssessmentsFactory.CreateLetterFormAssessment()
- [ ] design the QUESTION: how to ask for the desired form?

**Comment by CatmanIta** [comment]
I integrated the builder, but how should the assessment be? 
How can the player decide which variation to select?
These are the current parameters, but I am not sure how it should work.


            context.GameDescription = LocalizationDataId.Assessment_Select_Letter_Listen;   // TODO: should have another ID
            AssessmentOptions.Instance.PronunceQuestionWhenClicked = true;
            AssessmentOptions.Instance.PronunceAnswerWhenClicked = false; // Child shuold identify the letter
            AssessmentOptions.Instance.QuestionSpawnedPlaySound = true; // pronunce the word to sort
            AssessmentOptions.Instance.QuestionAnsweredPlaySound = true;
            AssessmentOptions.Instance.QuestionAnsweredFlip = true;
            AssessmentOptions.Instance.ShowQuestionAsImage = false;
            AssessmentOptions.Instance.PlayQuestionAlsoAfterTutorial = true;

**Comment by StefanoCecere** [comment]
i agree this is a new problem to check with Safa. @FrancyCavallari
