### ISSUE TITLE
Epic 11.11

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#7]
- [x] A) All Database (minigames, words, Course...)
- [x] B) Mood selector (same as now)
- [x] C) Game Selector
- [x] D) All stage 1 playable (Teacher calling all minigames with good data)
- [x] E) All minigames to be played in Stage 1 (letter ones) fully working (states, UI, rewards)
- [x] F) Home / Journey Map (stage 1) + link to Book scene, Player profile scene, Antura Space
- [x] G) Basic user profile scene (window + text data and wireframes)
- [x] H) basic logging (Log Manager)
- [x] I) creation / selection of player profile (draft)
- [x] L) Antura Space scene (as current end scene + some letters)
- [x] M) Assessment (current polished and debugged)
- [x] N) One MiniGame Tutorial (Maze?)
