### ISSUE TITLE
[Android] Kiosk mode

### ISSUE THREAD

**Issue by StefanoCecere** [vgwb/Antura_arabic#736]
we need a  kiosk mode for the Android platform, 

- [ ] the app uses a demo player in home:kiosk -> fastcrowd.
- [ ] web view to opne http://antura.org/kiosk/
- [ ] disable Back button for Quit
- [ ] disable any "exit" button, ... button
- [ ] if possibile, the app goes back to home_kiosk anfter 2 minutes of inactivity
